version: '2'
services:
    base:
        build:
            context: .
            dockerfile: base/Dockerfile
        image:  itamtao/base
    base.db:
        build:
            context: .
            dockerfile: base-with-db/Dockerfile
        image:  itamtao/base-db
        depends_on:
          - base
    pytorch:
        build:
            context: .
            dockerfile: pytorch/Dockerfile
        image:  itamtao/pytorch
        depends_on:
          - base.db
    # pytorch-mpi:
    #     build:
    #         context: .
    #         dockerfile: pytorch-mpi/Dockerfile
    #     image:  itamtao/pytorch-mpi
    #     depends_on:
    #       - base.db

